[project]
name = "lineage-harvester"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.3.1",
    "requests>=2.32.4",
    "pyarrow>=17.0.0",
]
